// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm4p90hioUuGyErZBrQuQ8sGVxu2RNtck',
    appId: '1:950039655427:web:b4de327b06b12f059a4a36',
    messagingSenderId: '950039655427',
    projectId: 'task-manager-b8e81',
    authDomain: 'task-manager-b8e81.firebaseapp.com',
    storageBucket: 'task-manager-b8e81.firebasestorage.app',
    measurementId: 'G-2X8JYF5PQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg9FYdqoMEWf8vQqTK3SNZ0d9lYY3KAKM',
    appId: '1:950039655427:android:14cafb172f46e6f89a4a36',
    messagingSenderId: '950039655427',
    projectId: 'task-manager-b8e81',
    storageBucket: 'task-manager-b8e81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV11kbpEoQQO7FA7HFaHCmRk1g7P98BN4',
    appId: '1:950039655427:ios:e0ae103f8668f3d99a4a36',
    messagingSenderId: '950039655427',
    projectId: 'task-manager-b8e81',
    storageBucket: 'task-manager-b8e81.firebasestorage.app',
    iosBundleId: 'com.example.taskapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV11kbpEoQQO7FA7HFaHCmRk1g7P98BN4',
    appId: '1:950039655427:ios:e0ae103f8668f3d99a4a36',
    messagingSenderId: '950039655427',
    projectId: 'task-manager-b8e81',
    storageBucket: 'task-manager-b8e81.firebasestorage.app',
    iosBundleId: 'com.example.taskapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm4p90hioUuGyErZBrQuQ8sGVxu2RNtck',
    appId: '1:950039655427:web:9eb0b221d8b2afe49a4a36',
    messagingSenderId: '950039655427',
    projectId: 'task-manager-b8e81',
    authDomain: 'task-manager-b8e81.firebaseapp.com',
    storageBucket: 'task-manager-b8e81.firebasestorage.app',
    measurementId: 'G-7KNHPB75P1',
  );
}
